### ISSUE TITLE
Rename variables using reserved keywords

### ISSUE THREAD

**Issue by dereckson** [beltoforion/muparser#22] opened 2016-03-10 18:54 UTC
According the C++ specification, the `const` word, already reserved is C, is a reserved word.

Yet, the source code uses `const string_type& GetMsg() const;` in `include/muParserError.h`.

**Reference**

http://cs.smu.ca/~porter/csc/ref/cpp_keywords.html

**Comment by beltoforion** [comment] 2016-03-11 18:31
muparser is using the const keyword for the very purpose it was reverved for. In case you are new to C++. This is called const correctness and considered good programming practice. For more details please read http://www.cprogramming.com/tutorial/const_correctness.html. I can also recommend the corresponding article in the C++ faq at http://www.parashift.com/c++-faq/const-correctness.html. 

In case you are not new to C++. I feel violated by your trolling. Please leave me alone.

**Comment by dereckson** [comment] 2016-03-11 23:28
Thank you for the precision.

I've seen the issue when helping a member of our local hackerspace with a linker issue (`termplot.cpp:(.text+0x3a2): undefined reference to `mu::ParserError::GetMsg() const'`). I were puzzled by this const, now I see where it comes from.

**Comment by beltoforion** [comment] 2016-03-12 00:04
Thanks for the clarification. If i had to place a bet i would the issue was a conflict related to the string type. Namely std::wstring vs. std::string. The string type is set with string_type depending on whether the UNICODE preprocessor definition is set or not. I should probably write a FAQ, this is the singlemost frequent problem.

**Comment by beltoforion** [comment] 2016-03-25 21:54
closing the issue since it is not a bug

**Closed by beltoforion** 2016-03-25 21:54 UTC
Labels: invalid
